### ISSUE TITLE
Example code doesn't show all found services

### ISSUE THREAD

**Issue by egaga** [Nimrodda/flutter_nsd#8]
When discovery gives multiple returned values immediately, the example code skips showing some of the values.

Is the following code in the example intended to work properly?

```dart
child: StreamBuilder(
    stream: flutterNsd.stream,
    builder: (context, snapshot) {
        if (snapshot.hasData) {
        services.add(snapshot.data as NsdServiceInfo);
```

Is the code guaranteed to add every found service to `services`? In my environment it doesn't seem so. The following code shows more found services in console than what the UI does.
 
```dart
flutterNsd.stream.listen((value) {
      print(value);
}
 ```

**Comment by egaga** [comment]
This can be reproduced (at least) using an iOS device using the latest flutter package release.
This might not be reproducible in the latest unreleased Android code that resolves services one-by-one.

**Comment by Nimrodda** [comment]
It might be that Flutter's StreamBuilder has some limitations and it can't handle quick updates. In my test environment I have only one service. Then again the example is just _an example_ :) You can implement the UI the way you want and completely ignore the StreamBuilder. How do you reproduce it btw?

**Comment by unelma** [comment]
I repreduced it by registering multiple instances for one service type.
e.g. In macOS, by using `dns-sd` tool:

```
dns-sd -R MyJsonServer1 _http._tcp . 3000 foo=bar
dns-sd -R MyJsonServer2 _http._tcp . 3000 x=y
dns-sd -R MyJsonServer3 _http._tcp . 3000 some=thing
```
Before running those, I have json-server setup like this `json-server --watch db.json --H 0.0.0.0 -p 3000`.

Something like that. In my case I actually have two local machines in the same local WIFI-network that have `_http._tcp` services, but I'm pretty sure that the problem shows up with only one.

Then I debugged the example using `_http._tcp` service type using usb-connected iPhone.
I don't see all the services, just a subset. But in the `listen` callback, I do see all of it.

**Comment by Nimrodda** [comment]
Thanks for the detailed repro steps. dns-sd sounds very useful 👍 
We might need the same queue solution on iOS to fix this.
If you're in a rush and have the time to take a look, a PR would be greatly appreciated.

**Comment by unelma** [comment]
My current limited guess is that the example code is problematic, not iOS code. True enough, changing the iOS code to be queue-like would probably make the example work, but then the resolving would be a little bit slower, and in a network with many instances it would degrade the overall user experience as the devices won't show up as fast as they could.

I could be totally wrong on this, though. I'm new to flutter/Dart so not sure about this. So personally, I think I try to find a way to use the API so that all devices are found, and if I notice that the iOS-NSD-plugin is problematic, then I'll investigate it further. 

Also, one could think that making a queue for both Android and iOS makes things consistent, but I would not think it's a good idea in this context only for consistency's sake (assumption here: iOS would work also without a queue).

**Comment by Nimrodda** [comment]
The example code is now fixed. It was a bad idea to use `StreamBuilder`. Check out ad98a89 for more info.

**Comment by egaga** [comment]
Thank you!
